# Generated by Django 2.2 on 2020-09-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionAnswer', models.CharField(max_length=30)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions_teacher')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
    ]
