# Generated by Django 2.2 on 2020-09-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('questions', '0001_initial'),
        ('gameHistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='questionID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.Questions_teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='studentID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
            preserve_default=False,
        ),
    ]
