# Generated by Django 2.2 on 2020-09-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionBody', models.CharField(max_length=200)),
                ('isMCQ', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions_student',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Questions')),
                ('Proposer', models.CharField(max_length=30)),
                ('isApproved', models.BooleanField(default=False)),
            ],
            bases=('questions.questions',),
        ),
        migrations.CreateModel(
            name='Questions_teacher',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Questions')),
                ('world', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('questionLevel', models.IntegerField(default=0)),
            ],
            bases=('questions.questions',),
        ),
        migrations.CreateModel(
            name='Questions_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=200)),
                ('isCorrect', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions')),
            ],
        ),
    ]
