# Generated by Django 2.2 on 2020-09-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200908_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions_answer',
            old_name='TquestionID',
            new_name='questionID',
        ),
    ]
