# Generated by Django 2.2 on 2020-09-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200908_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_teacher',
            name='questionLevel',
            field=models.IntegerField(default=0),
        ),
    ]
